import Head from "next/head";
import ForecastCard from "../components/ForecastCard";
import MapInformation from "../components/MapInformation";
import WeatherCard from "../components/WeatherCard";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.left}>
          <WeatherCard />
          <ForecastCard />
        </div>

        <div className={styles.right}>
          <MapInformation />
        </div>
      </main>
    </div>
  );
}
